development:
  adapter: postgresql
  encoding: utf8
  database: little_world_development
  username: postgres
  password: 123844

test:
  adapter: postgresql
  encoding: utf8
  database: little_world_test
  username: postgres
  password: 123844